---
abstract: 'Glues a cache to your PSGI application'
author:
  - 'Jakob Voss'
build_requires:
  Clone: 0
  Plack::Builder: 0
  Test::More: 0
  overload: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300018, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Cached
requires:
  Carp: 0
  Plack::Middleware: 0
  Plack::Util::Accessor: 0
  Scalar::Util: 0
  parent: 0
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/nichtich/Plack-Middleware-Cached/issues
  homepage: https://github.com/nichtich/Plack-Middleware-Cached
  repository: https://github.com/nichtich/Plack-Middleware-Cached.git
version: 0.13
