---
abstract: 'Glues a cache to your PSGI application'
author:
  - 'Jakob Voss'
build_requires:
  Plack::Builder: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Cached
requires:
  Carp: 0
  Plack::Middleware: 0
  Plack::Util::Accessor: 0
  Scalar::Util: 0
  overload: 0
  parent: 0
resources:
  bugtracker: https://github.com/nichtich/Plack-Middleware-CHI/issues
  repository: https://github.com/nichtich/Plack-Middleware-CHI
version: 0.11
